"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Payload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Algorithm(metaclass=_Algorithm):
        V = typing.NewType('V', builtins.int)

    ALGORITHM_UNSPECIFIED = Payload.Algorithm.V(0)
    ALGORITHM_SHA1 = Payload.Algorithm.V(1)
    ALGORITHM_SHA256 = Payload.Algorithm.V(2)
    ALGORITHM_SHA512 = Payload.Algorithm.V(3)
    ALGORITHM_MD5 = Payload.Algorithm.V(4)

    class _Algorithm(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Algorithm.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        ALGORITHM_UNSPECIFIED = Payload.Algorithm.V(0)
        ALGORITHM_SHA1 = Payload.Algorithm.V(1)
        ALGORITHM_SHA256 = Payload.Algorithm.V(2)
        ALGORITHM_SHA512 = Payload.Algorithm.V(3)
        ALGORITHM_MD5 = Payload.Algorithm.V(4)

    class DigitCount(metaclass=_DigitCount):
        V = typing.NewType('V', builtins.int)

    DIGIT_COUNT_UNSPECIFIED = Payload.DigitCount.V(0)
    DIGIT_COUNT_SIX = Payload.DigitCount.V(1)
    DIGIT_COUNT_EIGHT = Payload.DigitCount.V(2)

    class _DigitCount(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DigitCount.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        DIGIT_COUNT_UNSPECIFIED = Payload.DigitCount.V(0)
        DIGIT_COUNT_SIX = Payload.DigitCount.V(1)
        DIGIT_COUNT_EIGHT = Payload.DigitCount.V(2)

    class OtpType(metaclass=_OtpType):
        V = typing.NewType('V', builtins.int)

    OTP_TYPE_UNSPECIFIED = Payload.OtpType.V(0)
    OTP_TYPE_HOTP = Payload.OtpType.V(1)
    OTP_TYPE_TOTP = Payload.OtpType.V(2)

    class _OtpType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[OtpType.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        OTP_TYPE_UNSPECIFIED = Payload.OtpType.V(0)
        OTP_TYPE_HOTP = Payload.OtpType.V(1)
        OTP_TYPE_TOTP = Payload.OtpType.V(2)

    class OtpParameters(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        SECRET_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        ISSUER_FIELD_NUMBER: builtins.int
        ALGORITHM_FIELD_NUMBER: builtins.int
        DIGITS_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        COUNTER_FIELD_NUMBER: builtins.int
        secret: builtins.bytes = ...
        name: typing.Text = ...
        issuer: typing.Text = ...
        algorithm: global___Payload.Algorithm.V = ...
        digits: global___Payload.DigitCount.V = ...
        type: global___Payload.OtpType.V = ...
        counter: builtins.int = ...

        def __init__(self,
            *,
            secret : builtins.bytes = ...,
            name : typing.Text = ...,
            issuer : typing.Text = ...,
            algorithm : global___Payload.Algorithm.V = ...,
            digits : global___Payload.DigitCount.V = ...,
            type : global___Payload.OtpType.V = ...,
            counter : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"algorithm",b"algorithm",u"counter",b"counter",u"digits",b"digits",u"issuer",b"issuer",u"name",b"name",u"secret",b"secret",u"type",b"type"]) -> None: ...

    OTP_PARAMETERS_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    BATCH_SIZE_FIELD_NUMBER: builtins.int
    BATCH_INDEX_FIELD_NUMBER: builtins.int
    BATCH_ID_FIELD_NUMBER: builtins.int
    version: builtins.int = ...
    batch_size: builtins.int = ...
    batch_index: builtins.int = ...
    batch_id: builtins.int = ...

    @property
    def otp_parameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Payload.OtpParameters]: ...

    def __init__(self,
        *,
        otp_parameters : typing.Optional[typing.Iterable[global___Payload.OtpParameters]] = ...,
        version : builtins.int = ...,
        batch_size : builtins.int = ...,
        batch_index : builtins.int = ...,
        batch_id : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"batch_id",b"batch_id",u"batch_index",b"batch_index",u"batch_size",b"batch_size",u"otp_parameters",b"otp_parameters",u"version",b"version"]) -> None: ...
global___Payload = Payload
